# render.yaml
databases:
  - name: concrete-db
    plan: free

services:
  - type: web
    name: concrete-api
    env: docker
    repo: https://github.com/MoussaInc/concrete-strength
    region: frankfurt
    plan: free
    dockerfilePath: docker/api/Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      # If using Render Postgres
      - key: DATABASE_URL
        fromDatabase:
          name: concrete-db
          property: connectionString
      # CORS: pass dashboard host, build full origin in code
      - key: DASH_ORIGIN_HOST
        fromService:
          type: web
          name: concrete-dashboard
          property: host

  - type: web
    name: concrete-dashboard
    env: docker
    repo: https://github.com/MoussaInc/concrete-strength
    region: frankfurt
    plan: free
    dockerfilePath: docker/dashboard/Dockerfile
    autoDeploy: true
    envVars:
      # Get API host, build full URL in code
      - key: API_HOST
        fromService:
          type: web
          name: concrete-api
          property: host
